#!/usr/bin/env sh

# -----------------------------
# Layout and placement
# -----------------------------

# default layout (can be bsp, stack or float)
yabai -m config layout bsp

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# -----------------------------
# Gaps and padding
# -----------------------------

padding=8
yabai -m config top_padding $padding
yabai -m config bottom_padding $padding
yabai -m config left_padding $padding
yabai -m config right_padding $padding
yabai -m config window_gap $padding

# -----------------------------
# Mouse behavior
# -----------------------------

# center mouse on window with focus
yabai -m config mouse_follows_focus on

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move     # alt + left-click drag to move window
yabai -m config mouse_action2 resize   # alt + right-click drag to resize window

# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m mouse_drop_action swap

# -----------------------------
# Rules (floating / unmanaged apps)
# -----------------------------

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^AppCleaner$" manage=off

# -----------------------------
# Borders
# -----------------------------

borders active_color=0xffffb347 inactive_color=0x00000000 width=6.0 hidpi=on ax_focus=on &
